# Based on https://catalog.redhat.com/software/containers/ubi8-micro/601a84aadd19c7786c47c8ea?container-tabs
# Also see https://github.com/AlmaLinux/docker-images/blob/master/dockerfiles/alma9/Dockerfile.micro
ARG VERSION_ID
FROM registry.fedoraproject.org/fedora:${VERSION_ID} AS release
RUN source /etc/os-release && \
    dnf install --releasever $VERSION_ID -y \
    --setopt install_weak_deps=false \
    python3 python3-pip curl wget jq fish && \
    dnf list installed > /etc/PACKAGES && \
    dnf clean all && \
    /bin/date +%Y%m%d_%H%M > /etc/BUILDTIME

LABEL maintainer="np22-jpg"

LABEL name="np22-jpg/fedora-python3-dev"
LABEL summary="Unofficial Fedora python3 development image."
LABEL description="A not-so-light image built for developing python3 apps. Keeps in sync with fedora-python3."

CMD /usr/bin/fish