# Based on https://catalog.redhat.com/software/containers/ubi8-micro/601a84aadd19c7786c47c8ea?container-tabs
# Also see https://github.com/AlmaLinux/docker-images/blob/master/dockerfiles/alma9/Dockerfile.micro

FROM registry.access.redhat.com/ubi9 AS build
COPY --from=registry.access.redhat.com/ubi9/ubi-micro / /rootfs
RUN source /etc/os-release && \
    if [[ $TARGETARCH == arm64 ]]; then TARGETARCH=aarch64; fi && \
    dnf module enable --releasever $VERSION_ID -y --installroot /rootfs \
    --setopt=cachedir=/var/cache/dnf  \
    nodejs:18/minimal && \
    dnf install --releasever / --nodocs -y \
    --installroot /rootfs --setopt install_weak_deps=false \
    --setopt=cachedir=/var/cache/dnf \
    nodejs curl-minimal && \
    dnf --installroot /rootfs list installed > /rootfs/etc/PACKAGES && \
    dnf --installroot /rootfs clean all && \
    rm -rf /rootfs/var/log/dnf* /rootfs/var/log/yum.* && \
    echo "node:x:1000:" >> /rootfs/etc/group && \
    echo "node:x:1000:1000::/app:/bin/bash" >> /rootfs/etc/passwd && \
    /bin/date +%Y%m%d_%H%M > /rootfs/etc/BUILDTIME

FROM scratch AS fedora-micro
LABEL maintainer="np22-jpg"

LABEL name="np22-jpg/fedora-node"

#label for EULA
# LABEL com.fedora.license_terms="https://docs.fedoraproject.org/en-US/legal/"

#labels for container catalog
LABEL summary="Unofficial UBI node micro image"
LABEL description="Very small image which doesn't install the package manager."
LABEL io.k8s.display-name="fedora-node"
# LABEL io.openshift.expose-services=""

COPY --from=build /rootfs/ /
COPY --from=build /etc/yum.repos.d/ubi.repo /etc/yum.repos.d/ubi.repo
CMD /usr/bin/node