# Based on https://catalog.redhat.com/software/containers/ubi8-micro/601a84aadd19c7786c47c8ea?container-tabs
# Also see https://github.com/AlmaLinux/docker-images/blob/master/dockerfiles/alma9/Dockerfile.micro
ARG VERSION_ID
FROM registry.fedoraproject.org/fedora:${VERSION_ID} AS python-build
WORKDIR /usr/src/python
RUN dnf install --nodocs -y --setopt install_weak_deps=false \
    autoconf bluez-libs-devel bzip2 bzip2-devel desktop-file-utils \
    expat-devel findutils gcc-c++ gdb gdbm-devel git-core \
    glibc-all-langpacks glibc-devel gmp-devel gnupg2 libGL-devel \
    libX11-devel libappstream-glib libb2-devel libffi-devel \
    libnsl2-devel libtirpc-devel libuuid-devel make mpdecimal-devel \
    ncurses-devel openssl-devel pkgconfig python-pip-wheel \
    python-setuptools-wheel python3-rpm-generators python3.11 \
    readline-devel rsync sqlite-devel tar tcl-devel tix-devel tk-devel \
    tzdata valgrind-devel xz xz-devel zlib-devel && \
    curl -f https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz | \
    tar -xJC /usr/src/python --strip-components=1 && \
    	./configure \
		--enable-loadable-sqlite-extensions \
		--enable-optimizations \
		--enable-option-checking=fatal \
		--enable-shared \
		--with-lto \
		--with-system-expat \
		--without-ensurepip && \
    LDFLAGS="-s -w" make -j$(nproc) && \
    make install && \
    rsync -vr \
        --exclude *.pyc \
        --exclude *.pyo \
        --exclude test \
        --exclude tests \
        --exclude idle_test \
        --exclude libpython*a \ 
        /usr/local /python

FROM registry.fedoraproject.org/fedora:${VERSION_ID} AS fedora-micro-build
# ARG TARGETARCH
RUN mkdir /rootfs
COPY --from=python-build /python /rootfs
RUN source /etc/os-release && \
    dnf install --releasever $VERSION_ID --nodocs -y \
    --installroot /rootfs --setopt install_weak_deps=false \
    # --forcearch=$TARGETARCH \
    --setopt=cachedir=/var/cache/dnf \
    coreutils-single glibc-minimal-langpack && \
    dnf --installroot /rootfs list installed > /rootfs/etc/PACKAGES && \
    dnf --installroot /rootfs clean all && \
    rm -rf /rootfs/var/log/dnf* /rootfs/var/log/yum.* && \
    echo "app:x:1000:" >> /rootfs/etc/group && \
    echo "app:x:1000:1000::/app:/bin/bash" >> /rootfs/etc/passwd && \
    /bin/date +%Y%m%d_%H%M > /rootfs/etc/BUILDTIME

FROM scratch AS fedora-micro
LABEL maintainer="np22-jpg"

LABEL name="np22-jpg/fedora-python3"

#label for EULA
# LABEL com.fedora.license_terms="https://docs.fedoraproject.org/en-US/legal/"

#labels for container catalog
LABEL summary="Unofficial Fedora python3 micro image"
LABEL description="Very small image which doesn't install the package manager."
LABEL io.k8s.display-name="fedora-python3"
# LABEL io.openshift.expose-services=""

COPY --from=fedora-micro-build /rootfs/ /
COPY --from=fedora-micro-build /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo
CMD /usr/bin/python3