# Based on https://catalog.redhat.com/software/containers/ubi8-micro/601a84aadd19c7786c47c8ea?container-tabs
# Also see https://github.com/AlmaLinux/docker-images/blob/master/dockerfiles/alma9/Dockerfile.micro
ARG VERSION_ID
FROM --platform=$BUILDPLATFORM quay.io/fedora/fedora:${VERSION_ID} AS fedora-micro-build
ARG TARGETARCH
RUN mkdir /rootfs
RUN source /etc/os-release && \
    dnf install --releasever $VERSION_ID --nodocs -y \
    --installroot /rootfs --setopt install_weak_deps=false \
    --forcearch=$TARGETARCH \
    --setopt=cachedir=/var/cache/dnf \
    coreutils-single glibc-minimal-langpack python3 && \
    dnf --installroot /rootfs list installed > /rootfs/etc/PACKAGES && \
    dnf --installroot /rootfs clean all && \
    rm -rf /rootfs/var/log/dnf* /rootfs/var/log/yum.* && \
    echo "app:x:1000:" >> /rootfs/etc/group && \
    echo "app:x:1000:1000::/app:/bin/bash" >> /rootfs/etc/passwd && \
    /bin/date +%Y%m%d_%H%M > /rootfs/etc/BUILDTIME

FROM scratch AS fedora-micro
LABEL maintainer="np22-jpg"

LABEL name="np22-jpg/fedora-python3"
LABEL version="$VERSION_ID"

#label for EULA
# LABEL com.fedora.license_terms="https://docs.fedoraproject.org/en-US/legal/"

#labels for container catalog
LABEL summary="Unofficial Fedora python3 micro image"
LABEL description="Very small image which doesn't install the package manager."
LABEL io.k8s.display-name="fedora-python3"
# LABEL io.openshift.expose-services=""

COPY --from=fedora-micro-build /rootfs/ /
COPY --from=fedora-micro-build /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo
CMD /usr/bin/python3