name: fedora-micro

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '20 03 * * *'  # 3:20am everyday

# I don't think anyone will use these with s390x
env:
  ARCH: linux/amd64,linux/arm64,linux/ppc64le
  CONTAINERFILE: micro/Containerfile
  REPO: quay.io/np22-jpg/fedora-micro

jobs:
  build_and_push_docker_images:
    strategy:
      fail-fast: false
      matrix:
        version: [36, 37, 38, 39]
        include:
          - version: 37
            tag: latest
          - version: 39
            tag: rawhide
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container:
    #   image: quay.io/buildah/stable:latest
    #   options: --user root

    name: Push Docker image to Quay
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install qemu and dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static dnf
      - name: Check for changes
        run: |
          chmod +x ./check_for_rpm_changes.sh
          sudo ./check_for_rpm_changes.sh ${{ env.REPO }}:${{ matrix.version }} ${{ env.CONTAINERFILE }}

      - id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: fedora-micro
          tags: ${{ github.sha }} ${{ matrix.version }} ${{ matrix.tag }}
          containerfiles: |
            ./${{ env.CONTAINERFILE }}
          archs: ${{ env.ARCH }}
          extra_args: VERSION_ID=${{ matrix.version }}

      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/np22-jpg
          username: np22-jpg+fedoramicro
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"