# Based on https://catalog.redhat.com/software/containers/ubi8-micro/601a84aadd19c7786c47c8ea?container-tabs
# Also see https://github.com/AlmaLinux/docker-images/blob/master/dockerfiles/alma9/Dockerfile.micro
ARG VERSION_ID
FROM registry.fedoraproject.org/fedora:${VERSION_ID} AS release
ARG NODE_VERSION
RUN source /etc/os-release && \
    dnf module enable --releasever $VERSION_ID -y \
    nodejs:$NODE_VERSION && \
    dnf install --releasever $VERSION_ID -y \
    --setopt install_weak_deps=false \
    nodejs npm curl wget jq fish && \
    dnf list installed > /etc/PACKAGES && \
    dnf clean all && \
    npm install -g npm@latest && \
    npm i -g yarn && \
    /bin/date +%Y%m%d_%H%M > /etc/BUILDTIME

LABEL maintainer="np22-jpg"

LABEL name="np22-jpg/fedora-npm"
LABEL summary="Unofficial Fedora npm image."
LABEL description="A not-so-light image built for developing nodejs apps. Keeps in sync with fedora-node."

CMD /usr/bin/fish